import type { NAICSCode } from './types'

// NAICS 2022 — representative set covering government contracting's most common sectors
export const NAICS_CODES: NAICSCode[] = [
  // 11 – Agriculture, Forestry, Fishing
  { code: '111110', title: 'Soybean Farming' },
  { code: '111150', title: 'Corn Farming' },
  { code: '111940', title: 'Hay Farming' },
  { code: '112111', title: 'Beef Cattle Ranching and Farming' },
  { code: '113110', title: 'Timber Tract Operations' },
  { code: '113310', title: 'Logging' },
  { code: '114111', title: 'Finfish Fishing' },
  { code: '115310', title: 'Support Activities for Forestry' },

  // 21 – Mining, Quarrying, Oil and Gas
  { code: '211120', title: 'Crude Petroleum Extraction' },
  { code: '211130', title: 'Natural Gas Extraction' },
  { code: '212111', title: 'Bituminous Coal and Lignite Surface Mining' },
  { code: '212311', title: 'Dimension Stone Mining and Quarrying' },
  { code: '213111', title: 'Drilling Oil and Gas Wells' },
  { code: '213112', title: 'Support Activities for Oil and Gas Operations' },

  // 22 – Utilities
  { code: '221111', title: 'Hydroelectric Power Generation' },
  { code: '221112', title: 'Fossil Fuel Electric Power Generation' },
  { code: '221113', title: 'Nuclear Electric Power Generation' },
  { code: '221114', title: 'Solar Electric Power Generation' },
  { code: '221115', title: 'Wind Electric Power Generation' },
  { code: '221118', title: 'Other Electric Power Generation' },
  { code: '221122', title: 'Electric Power Distribution' },
  { code: '221210', title: 'Natural Gas Distribution' },
  { code: '221310', title: 'Water Supply and Irrigation Systems' },
  { code: '221320', title: 'Sewage Treatment Facilities' },

  // 23 – Construction
  { code: '236115', title: 'New Single-Family Housing Construction' },
  { code: '236116', title: 'New Multifamily Housing Construction' },
  { code: '236210', title: 'Industrial Building Construction' },
  { code: '236220', title: 'Commercial and Institutional Building Construction' },
  { code: '237110', title: 'Water and Sewer Line and Related Structures Construction' },
  { code: '237120', title: 'Oil and Gas Pipeline and Related Structures Construction' },
  { code: '237130', title: 'Power and Communication Line and Related Structures Construction' },
  { code: '237210', title: 'Land Subdivision' },
  { code: '237310', title: 'Highway, Street, and Bridge Construction' },
  { code: '237990', title: 'Other Heavy and Civil Engineering Construction' },
  { code: '238110', title: 'Poured Concrete Foundation and Structure Contractors' },
  { code: '238120', title: 'Structural Steel and Precast Concrete Contractors' },
  { code: '238130', title: 'Framing Contractors' },
  { code: '238140', title: 'Masonry Contractors' },
  { code: '238150', title: 'Glass and Glazing Contractors' },
  { code: '238160', title: 'Roofing Contractors' },
  { code: '238170', title: 'Siding Contractors' },
  { code: '238190', title: 'Other Foundation, Structure, and Building Exterior Contractors' },
  { code: '238210', title: 'Electrical Contractors and Other Wiring Installation Contractors' },
  { code: '238220', title: 'Plumbing, Heating, and Air-Conditioning Contractors' },
  { code: '238290', title: 'Other Building Equipment Contractors' },
  { code: '238310', title: 'Drywall and Insulation Contractors' },
  { code: '238320', title: 'Painting and Wall Covering Contractors' },
  { code: '238330', title: 'Flooring Contractors' },
  { code: '238340', title: 'Tile and Terrazzo Contractors' },
  { code: '238350', title: 'Finish Carpentry Contractors' },
  { code: '238390', title: 'Other Building Finishing Contractors' },
  { code: '238910', title: 'Site Preparation Contractors' },
  { code: '238990', title: 'All Other Specialty Trade Contractors' },

  // 31-33 – Manufacturing (select codes)
  { code: '311110', title: 'Animal Food Manufacturing' },
  { code: '311230', title: 'Breakfast Cereal Manufacturing' },
  { code: '311511', title: 'Fluid Milk Manufacturing' },
  { code: '312111', title: 'Soft Drink Manufacturing' },
  { code: '315210', title: 'Cut and Sew Apparel Contractors' },
  { code: '321113', title: 'Sawmills' },
  { code: '322121', title: 'Paper Mills' },
  { code: '325110', title: 'Petrochemical Manufacturing' },
  { code: '325180', title: 'Other Basic Inorganic Chemical Manufacturing' },
  { code: '325411', title: 'Medicinal and Botanical Manufacturing' },
  { code: '325412', title: 'Pharmaceutical Preparation Manufacturing' },
  { code: '325413', title: 'In-Vitro Diagnostic Substance Manufacturing' },
  { code: '325414', title: 'Biological Product Manufacturing' },
  { code: '325510', title: 'Paint and Coating Manufacturing' },
  { code: '325611', title: 'Soap and Other Detergent Manufacturing' },
  { code: '325620', title: 'Toilet Preparation Manufacturing' },
  { code: '325910', title: 'Printing Ink Manufacturing' },
  { code: '326111', title: 'Plastics Bag and Pouch Manufacturing' },
  { code: '326211', title: 'Tire Manufacturing' },
  { code: '327110', title: 'Pottery, Ceramics, and Plumbing Fixture Manufacturing' },
  { code: '327310', title: 'Cement Manufacturing' },
  { code: '331110', title: 'Iron and Steel Mills and Ferroalloy Manufacturing' },
  { code: '331315', title: 'Aluminum Sheet, Plate, and Foil Manufacturing' },
  { code: '332110', title: 'Forging and Stamping' },
  { code: '332310', title: 'Plate Work Manufacturing' },
  { code: '332410', title: 'Power Boiler and Heat Exchanger Manufacturing' },
  { code: '332420', title: 'Metal Tank Manufacturing' },
  { code: '332510', title: 'Hardware Manufacturing' },
  { code: '332710', title: 'Machine Shops' },
  { code: '332720', title: 'Turned Product and Screw, Nut, and Bolt Manufacturing' },
  { code: '332810', title: 'Metal Heat Treating' },
  { code: '332911', title: 'Industrial Valve Manufacturing' },
  { code: '332991', title: 'Ball and Roller Bearing Manufacturing' },
  { code: '332999', title: 'All Other Miscellaneous Fabricated Metal Product Manufacturing' },
  { code: '333120', title: 'Construction Machinery Manufacturing' },
  { code: '333130', title: 'Mining, Oil and Gas Field Machinery and Equipment Manufacturing' },
  { code: '333249', title: 'Other Industrial Machinery Manufacturing' },
  { code: '333310', title: 'Commercial and Service Industry Machinery Manufacturing' },
  { code: '333413', title: 'Industrial and Commercial Fan and Blower and Air Purification Equipment Manufacturing' },
  { code: '333511', title: 'Industrial Mold Manufacturing' },
  { code: '333611', title: 'Turbine and Turbine Generator Set Units Manufacturing' },
  { code: '333612', title: 'Speed Changer, Industrial High-Speed Drive, and Gear Manufacturing' },
  { code: '333613', title: 'Mechanical Power Transmission Equipment Manufacturing' },
  { code: '333618', title: 'Other Engine Equipment Manufacturing' },
  { code: '333912', title: 'Air and Gas Compressor Manufacturing' },
  { code: '333914', title: 'Measuring, Dispensing, and Other Pumping Equipment Manufacturing' },
  { code: '333920', title: 'Material Handling Equipment Manufacturing' },
  { code: '333991', title: 'Power-Driven Handtool Manufacturing' },
  { code: '334111', title: 'Electronic Computer Manufacturing' },
  { code: '334112', title: 'Computer Storage Device Manufacturing' },
  { code: '334118', title: 'Computer Terminal and Other Computer Peripheral Equipment Manufacturing' },
  { code: '334210', title: 'Telephone Apparatus Manufacturing' },
  { code: '334220', title: 'Radio and Television Broadcasting and Wireless Communications Equipment Manufacturing' },
  { code: '334290', title: 'Other Communications Equipment Manufacturing' },
  { code: '334310', title: 'Audio and Video Equipment Manufacturing' },
  { code: '334412', title: 'Bare Printed Circuit Board Manufacturing' },
  { code: '334413', title: 'Semiconductor and Related Device Manufacturing' },
  { code: '334416', title: 'Capacitor, Resistor, Coil, Transformer, and Other Inductor Manufacturing' },
  { code: '334417', title: 'Electronic Connector Manufacturing' },
  { code: '334419', title: 'Other Electronic Component Manufacturing' },
  { code: '334510', title: 'Electromedical and Electrotherapeutic Apparatus Manufacturing' },
  { code: '334511', title: 'Search, Detection, Navigation, Guidance, Aeronautical Systems Manufacturing' },
  { code: '334512', title: 'Automatic Environmental Control Manufacturing for Residential, Commercial, and Appliance Use' },
  { code: '334513', title: 'Instruments and Related Products Manufacturing for Measuring, Displaying' },
  { code: '334514', title: 'Totalizing Fluid Meter and Counting Device Manufacturing' },
  { code: '334515', title: 'Instrument Manufacturing for Measuring and Testing Electricity' },
  { code: '334516', title: 'Analytical Laboratory Instrument Manufacturing' },
  { code: '334517', title: 'Irradiation Apparatus Manufacturing' },
  { code: '334519', title: 'Other Measuring and Controlling Device Manufacturing' },
  { code: '334614', title: 'Software and Other Prerecorded Compact Disc, Tape, and Record Reproducing' },
  { code: '335110', title: 'Electric Lamp Bulb and Part Manufacturing' },
  { code: '335121', title: 'Residential Electric Lighting Fixture Manufacturing' },
  { code: '335122', title: 'Commercial, Industrial, and Institutional Electric Lighting Fixture Manufacturing' },
  { code: '335129', title: 'Other Lighting Equipment Manufacturing' },
  { code: '335210', title: 'Small Electrical Appliance Manufacturing' },
  { code: '335220', title: 'Major Household Appliance Manufacturing' },
  { code: '335311', title: 'Power, Distribution, and Specialty Transformer Manufacturing' },
  { code: '335312', title: 'Motor and Generator Manufacturing' },
  { code: '335313', title: 'Switchgear and Switchboard Apparatus Manufacturing' },
  { code: '335314', title: 'Relay and Industrial Control Manufacturing' },
  { code: '335910', title: 'Battery Manufacturing' },
  { code: '336111', title: 'Automobile Manufacturing' },
  { code: '336120', title: 'Heavy Duty Truck Manufacturing' },
  { code: '336211', title: 'Motor Vehicle Body Manufacturing' },
  { code: '336212', title: 'Truck Trailer Manufacturing' },
  { code: '336310', title: 'Motor Vehicle Gasoline Engine and Engine Parts Manufacturing' },
  { code: '336320', title: 'Motor Vehicle Electrical and Electronic Equipment Manufacturing' },
  { code: '336330', title: 'Motor Vehicle Steering and Suspension Components Manufacturing' },
  { code: '336340', title: 'Motor Vehicle Brake System Manufacturing' },
  { code: '336350', title: 'Motor Vehicle Transmission and Power Train Parts Manufacturing' },
  { code: '336360', title: 'Motor Vehicle Seating and Interior Trim Manufacturing' },
  { code: '336370', title: 'Motor Vehicle Metal Stamping' },
  { code: '336390', title: 'Other Motor Vehicle Parts Manufacturing' },
  { code: '336411', title: 'Aircraft Manufacturing' },
  { code: '336412', title: 'Aircraft Engine and Engine Parts Manufacturing' },
  { code: '336413', title: 'Other Aircraft Parts and Auxiliary Equipment Manufacturing' },
  { code: '336414', title: 'Guided Missile and Space Vehicle Manufacturing' },
  { code: '336415', title: 'Guided Missile and Space Vehicle Propulsion Unit Manufacturing' },
  { code: '336419', title: 'Other Guided Missile and Space Vehicle Parts Manufacturing' },
  { code: '336510', title: 'Railroad Rolling Stock Manufacturing' },
  { code: '336611', title: 'Ship Building and Repairing' },
  { code: '336612', title: 'Boat Building' },
  { code: '336992', title: 'Military Armored Vehicle, Tank, and Tank Component Manufacturing' },
  { code: '336999', title: 'All Other Transportation Equipment Manufacturing' },
  { code: '337110', title: 'Wood Kitchen Cabinet and Countertop Manufacturing' },
  { code: '339112', title: 'Surgical and Medical Instrument Manufacturing' },
  { code: '339113', title: 'Surgical Appliance and Supplies Manufacturing' },
  { code: '339114', title: 'Dental Equipment and Supplies Manufacturing' },
  { code: '339115', title: 'Ophthalmic Goods Manufacturing' },
  { code: '339116', title: 'Dental Laboratories' },
  { code: '339910', title: 'Jewelry and Silverware Manufacturing' },
  { code: '339920', title: 'Sporting and Athletic Goods Manufacturing' },

  // 42 – Wholesale Trade
  { code: '423430', title: 'Computer and Computer Peripherals Equipment and Software Merchant Wholesalers' },
  { code: '423450', title: 'Medical, Dental, and Hospital Equipment and Supplies Merchant Wholesalers' },
  { code: '423460', title: 'Ophthalmic Goods Merchant Wholesalers' },
  { code: '423490', title: 'Other Professional and Commercial Equipment and Supplies Merchant Wholesalers' },
  { code: '423610', title: 'Electrical Apparatus and Equipment, Wiring Supplies Merchant Wholesalers' },
  { code: '423690', title: 'Other Electronic Parts and Equipment Merchant Wholesalers' },
  { code: '423720', title: 'Plumbing and Heating Equipment and Supplies Merchant Wholesalers' },
  { code: '423810', title: 'Construction and Mining Machinery and Equipment Merchant Wholesalers' },
  { code: '423820', title: 'Farm and Garden Machinery and Equipment Merchant Wholesalers' },
  { code: '423830', title: 'Industrial and Personal Service Paper Merchant Wholesalers' },
  { code: '423860', title: 'Transportation Equipment and Supplies Merchant Wholesalers' },
  { code: '423990', title: 'Other Miscellaneous Durable Goods Merchant Wholesalers' },
  { code: '424410', title: 'General Line Grocery Merchant Wholesalers' },
  { code: '424490', title: 'Other Grocery and Related Products Merchant Wholesalers' },
  { code: '424610', title: 'Plastics Materials and Basic Forms and Shapes Merchant Wholesalers' },
  { code: '424690', title: 'Other Chemical and Allied Products Merchant Wholesalers' },
  { code: '424710', title: 'Petroleum Bulk Stations and Terminals' },
  { code: '424720', title: 'Petroleum and Petroleum Products Merchant Wholesalers' },
  { code: '424910', title: 'Farm Supplies Merchant Wholesalers' },

  // 48-49 – Transportation and Warehousing
  { code: '481111', title: 'Scheduled Passenger Air Transportation' },
  { code: '481112', title: 'Scheduled Freight Air Transportation' },
  { code: '481211', title: 'Nonscheduled Chartered Passenger Air Transportation' },
  { code: '481212', title: 'Nonscheduled Chartered Freight Air Transportation' },
  { code: '482111', title: 'Line-Haul Railroads' },
  { code: '483111', title: 'Deep Sea Freight Transportation' },
  { code: '483112', title: 'Deep Sea Passenger Transportation' },
  { code: '484110', title: 'General Freight Trucking, Local' },
  { code: '484121', title: 'General Freight Trucking, Long-Distance, Truckload' },
  { code: '484122', title: 'General Freight Trucking, Long-Distance, Less Than Truckload' },
  { code: '484210', title: 'Used Household and Office Goods Moving' },
  { code: '484220', title: 'Specialized Freight Trucking' },
  { code: '485111', title: 'Mixed Mode Transit Systems' },
  { code: '485112', title: 'Commuter Rail Systems' },
  { code: '485113', title: 'Bus and Other Motor Vehicle Transit Systems' },
  { code: '485210', title: 'Interurban and Rural Bus Transportation' },
  { code: '485310', title: 'Taxi Service' },
  { code: '485320', title: 'Limousine Service' },
  { code: '485410', title: 'School and Employee Bus Transportation' },
  { code: '485510', title: 'Charter Bus Industry' },
  { code: '485991', title: 'Special Needs Transportation' },
  { code: '485999', title: 'All Other Transit and Ground Passenger Transportation' },
  { code: '486110', title: 'Pipeline Transportation of Crude Oil' },
  { code: '487110', title: 'Scenic and Sightseeing Transportation, Land' },
  { code: '488111', title: 'Air Traffic Control' },
  { code: '488119', title: 'Other Airport Operations' },
  { code: '488190', title: 'Other Support Activities for Air Transportation' },
  { code: '488210', title: 'Support Activities for Rail Transportation' },
  { code: '488310', title: 'Port and Harbor Operations' },
  { code: '488320', title: 'Marine Cargo Handling' },
  { code: '488330', title: 'Navigational Services to Shipping' },
  { code: '488390', title: 'Other Support Activities for Water Transportation' },
  { code: '488410', title: 'Motor Vehicle Towing' },
  { code: '488490', title: 'Other Support Activities for Road Transportation' },
  { code: '488510', title: 'Freight Transportation Arrangement' },
  { code: '488991', title: 'Packing and Crating' },
  { code: '488999', title: 'All Other Support Activities for Transportation' },
  { code: '491110', title: 'Postal Service' },
  { code: '492110', title: 'Couriers and Express Delivery Services' },
  { code: '492210', title: 'Local Messengers and Local Delivery' },
  { code: '493110', title: 'General Warehousing and Storage' },
  { code: '493120', title: 'Refrigerated Warehousing and Storage' },
  { code: '493130', title: 'Farm Product Warehousing and Storage' },
  { code: '493190', title: 'Other Warehousing and Storage' },

  // 51 – Information
  { code: '511110', title: 'Newspaper Publishers' },
  { code: '511120', title: 'Periodical Publishers' },
  { code: '511130', title: 'Book Publishers' },
  { code: '511140', title: 'Directory and Mailing List Publishers' },
  { code: '511191', title: 'Greeting Card Publishers' },
  { code: '511199', title: 'All Other Publishers' },
  { code: '511210', title: 'Software Publishers' },
  { code: '512110', title: 'Motion Picture and Video Production' },
  { code: '512120', title: 'Motion Picture and Video Distribution' },
  { code: '512131', title: 'Motion Picture Theaters (except Drive-Ins)' },
  { code: '512132', title: 'Drive-In Motion Picture Theaters' },
  { code: '512191', title: 'Teleproduction and Other Postproduction Services' },
  { code: '512199', title: 'Other Motion Picture and Video Industries' },
  { code: '512210', title: 'Record Production and Distribution' },
  { code: '512230', title: 'Music Publishers' },
  { code: '512240', title: 'Sound Recording Studios' },
  { code: '512291', title: 'Agents and Managers for Artists, Athletes, Entertainers' },
  { code: '515111', title: 'Radio Networks' },
  { code: '515112', title: 'Radio Stations' },
  { code: '515120', title: 'Television Broadcasting' },
  { code: '515210', title: 'Cable and Other Subscription Programming' },
  { code: '516110', title: 'Radio Broadcasting' },
  { code: '516120', title: 'Television Broadcasting' },
  { code: '517111', title: 'Wired Telecommunications Carriers' },
  { code: '517112', title: 'Wireless Telecommunications Carriers (except Satellite)' },
  { code: '517121', title: 'Telephone Apparatus Manufacturing' },
  { code: '517311', title: 'Wired Telecommunications Carriers' },
  { code: '517312', title: 'Wireless Telecommunications Carriers (except Satellite)' },
  { code: '517319', title: 'Other Telecommunications' },
  { code: '517410', title: 'Satellite Telecommunications' },
  { code: '517919', title: 'All Other Telecommunications' },
  { code: '518210', title: 'Computing Infrastructure Providers, Data Processing, Web Hosting Services' },
  { code: '519130', title: 'Internet Publishing and Broadcasting and Web Search Portals' },
  { code: '519190', title: 'All Other Information Services' },

  // 52 – Finance and Insurance
  { code: '522110', title: 'Commercial Banking' },
  { code: '522120', title: 'Savings Institutions, Federally Chartered' },
  { code: '522130', title: 'Credit Unions, Federally Chartered' },
  { code: '522210', title: 'Credit Card Issuing' },
  { code: '522220', title: 'Sales Financing' },
  { code: '522291', title: 'Consumer Lending' },
  { code: '522292', title: 'Real Estate Credit' },
  { code: '522310', title: 'Mortgage and Nonmortgage Loan Brokers' },
  { code: '522390', title: 'Other Activities Related to Credit Intermediation' },
  { code: '523110', title: 'Investment Banking and Securities Dealing' },
  { code: '523120', title: 'Securities Brokerage' },
  { code: '523130', title: 'Commodity Contracts Dealing' },
  { code: '523910', title: 'Miscellaneous Intermediation' },
  { code: '523920', title: 'Portfolio Management' },
  { code: '523930', title: 'Investment Advice' },
  { code: '523991', title: 'Trust, Fiduciary, and Custody Activities' },
  { code: '523999', title: 'Miscellaneous Financial Investment Activities' },
  { code: '524113', title: 'Direct Life Insurance Carriers' },
  { code: '524114', title: 'Direct Health and Medical Insurance Carriers' },
  { code: '524126', title: 'Direct Property and Casualty Insurance Carriers' },
  { code: '524127', title: 'Direct Title Insurance Carriers' },
  { code: '524128', title: 'Other Direct Insurance Carriers' },
  { code: '524130', title: 'Reinsurance Carriers' },
  { code: '524210', title: 'Insurance Agencies and Brokerages' },
  { code: '524291', title: 'Claims Adjusting' },
  { code: '524292', title: 'Third Party Administration of Insurance and Pension Funds' },
  { code: '524298', title: 'All Other Insurance Related Activities' },
  { code: '525110', title: 'Pension Funds' },
  { code: '525120', title: 'Health and Welfare Funds' },
  { code: '525190', title: 'Other Insurance Funds' },
  { code: '525910', title: 'Open-End Investment Funds (Form N-1A)' },
  { code: '525990', title: 'Other Financial Vehicles' },

  // 54 – Professional, Scientific, and Technical Services (KEY for govt contracting)
  { code: '541110', title: 'Offices of Lawyers' },
  { code: '541120', title: 'Offices of Notaries' },
  { code: '541191', title: 'Title Abstract and Settlement Offices' },
  { code: '541199', title: 'All Other Legal Services' },
  { code: '541211', title: 'Offices of Certified Public Accountants' },
  { code: '541213', title: 'Tax Preparation Services' },
  { code: '541214', title: 'Payroll Services' },
  { code: '541219', title: 'Other Accounting Services' },
  { code: '541310', title: 'Architectural Services' },
  { code: '541320', title: 'Landscape Architectural Services' },
  { code: '541330', title: 'Engineering Services' },
  { code: '541340', title: 'Drafting Services' },
  { code: '541350', title: 'Building Inspection Services' },
  { code: '541360', title: 'Geophysical Surveying and Mapping Services' },
  { code: '541370', title: 'Surveying and Mapping Services' },
  { code: '541380', title: 'Testing Laboratories and Services' },
  { code: '541410', title: 'Interior Design Services' },
  { code: '541420', title: 'Industrial Design Services' },
  { code: '541430', title: 'Graphic Design Services' },
  { code: '541490', title: 'Other Specialized Design Services' },
  { code: '541511', title: 'Custom Computer Programming Services' },
  { code: '541512', title: 'Computer Systems Design Services' },
  { code: '541513', title: 'Computer Facilities Management Services' },
  { code: '541519', title: 'Other Computer Related Services' },
  { code: '541611', title: 'Administrative Management and General Management Consulting Services' },
  { code: '541612', title: 'Human Resources Consulting Services' },
  { code: '541613', title: 'Marketing Consulting Services' },
  { code: '541614', title: 'Process, Physical Distribution, and Logistics Consulting Services' },
  { code: '541618', title: 'Other Management Consulting Services' },
  { code: '541620', title: 'Environmental Consulting Services' },
  { code: '541690', title: 'Other Scientific and Technical Consulting Services' },
  { code: '541710', title: 'Research and Development in the Physical, Engineering, and Life Sciences' },
  { code: '541720', title: 'Research and Development in the Social Sciences and Humanities' },
  { code: '541810', title: 'Advertising Agencies' },
  { code: '541820', title: 'Public Relations Agencies' },
  { code: '541830', title: 'Media Buying Agencies' },
  { code: '541840', title: 'Media Representatives' },
  { code: '541850', title: 'Indoor and Outdoor Display Advertising' },
  { code: '541860', title: 'Direct Mail Advertising' },
  { code: '541870', title: 'Advertising Material Distribution Services' },
  { code: '541890', title: 'Other Services Related to Advertising' },
  { code: '541910', title: 'Marketing Research and Public Opinion Polling' },
  { code: '541921', title: 'Photography Studios, Portrait' },
  { code: '541922', title: 'Commercial Photography' },
  { code: '541930', title: 'Translation and Interpretation Services' },
  { code: '541940', title: 'Veterinary Services' },
  { code: '541990', title: 'All Other Professional, Scientific, and Technical Services' },

  // 55 – Management of Companies and Enterprises
  { code: '551111', title: 'Offices of Bank Holding Companies' },
  { code: '551112', title: 'Offices of Other Holding Companies' },
  { code: '551114', title: 'Corporate, Subsidiary, and Regional Managing Offices' },

  // 56 – Administrative and Support Services
  { code: '561110', title: 'Office Administrative Services' },
  { code: '561120', title: 'Facilities Support Services' },
  { code: '561210', title: 'Facilities Support Services' },
  { code: '561311', title: 'Employment Placement Agencies' },
  { code: '561312', title: 'Executive Search Services' },
  { code: '561320', title: 'Temporary Help Services' },
  { code: '561330', title: 'Professional Employer Organizations' },
  { code: '561410', title: 'Document Preparation Services' },
  { code: '561421', title: 'Telephone Answering Services' },
  { code: '561422', title: 'Telemarketing Bureaus and Other Contact Centers' },
  { code: '561431', title: 'Private Mail Centers' },
  { code: '561439', title: 'Other Business Service Centers' },
  { code: '561440', title: 'Collection Agencies' },
  { code: '561450', title: 'Credit Bureaus' },
  { code: '561491', title: 'Repossession Services' },
  { code: '561492', title: 'Court Reporting and Stenotype Services' },
  { code: '561499', title: 'All Other Business Support Services' },
  { code: '561510', title: 'Travel Agencies' },
  { code: '561520', title: 'Tour Operators' },
  { code: '561591', title: 'Convention and Visitors Bureaus' },
  { code: '561599', title: 'All Other Travel Arrangement and Reservation Services' },
  { code: '561611', title: 'Investigation Services' },
  { code: '561612', title: 'Security Guards and Patrol Services' },
  { code: '561613', title: 'Armored Car Services' },
  { code: '561621', title: 'Security Systems Services (except Locksmiths)' },
  { code: '561622', title: 'Locksmiths' },
  { code: '561710', title: 'Exterminating and Pest Control Services' },
  { code: '561720', title: 'Janitorial Services' },
  { code: '561730', title: 'Landscaping Services' },
  { code: '561740', title: 'Carpet and Upholstery Cleaning Services' },
  { code: '561790', title: 'Other Services to Buildings and Dwellings' },
  { code: '561910', title: 'Packaging and Labeling Services' },
  { code: '561920', title: 'Convention and Trade Show Organizers' },
  { code: '561990', title: 'All Other Support Services' },
  { code: '562111', title: 'Solid Waste Collection' },
  { code: '562112', title: 'Hazardous Waste Collection' },
  { code: '562119', title: 'Other Waste Collection' },
  { code: '562211', title: 'Hazardous Waste Treatment and Disposal' },
  { code: '562212', title: 'Solid Waste Landfill' },
  { code: '562213', title: 'Solid Waste Combustors and Incinerators' },
  { code: '562219', title: 'Other Nonhazardous Waste Treatment and Disposal' },
  { code: '562910', title: 'Remediation Services' },
  { code: '562920', title: 'Materials Recovery Facilities' },
  { code: '562991', title: 'Septic Tank and Related Services' },
  { code: '562998', title: 'All Other Miscellaneous Waste Management Services' },

  // 61 – Educational Services
  { code: '611110', title: 'Elementary and Secondary Schools' },
  { code: '611210', title: 'Junior Colleges' },
  { code: '611310', title: 'Colleges, Universities, and Professional Schools' },
  { code: '611410', title: 'Business and Secretarial Schools' },
  { code: '611420', title: 'Computer Training' },
  { code: '611430', title: 'Professional and Management Development Training' },
  { code: '611511', title: 'Cosmetology and Barber Schools' },
  { code: '611512', title: 'Flight Training' },
  { code: '611513', title: 'Apprenticeship Training' },
  { code: '611519', title: 'Other Technical and Trade Schools' },
  { code: '611610', title: 'Fine Arts Schools' },
  { code: '611620', title: 'Sports and Recreation Instruction' },
  { code: '611630', title: 'Language Schools' },
  { code: '611691', title: 'Exam Preparation and Tutoring' },
  { code: '611692', title: 'Automobile Driving Schools' },
  { code: '611699', title: 'All Other Miscellaneous Schools and Instruction' },
  { code: '611710', title: 'Educational Support Services' },

  // 62 – Health Care and Social Assistance (KEY for govt contracting)
  { code: '621111', title: 'Offices of Physicians (except Mental Health Specialists)' },
  { code: '621112', title: 'Offices of Physicians, Mental Health Specialists' },
  { code: '621210', title: 'Offices of Dentists' },
  { code: '621310', title: 'Offices of Chiropractors' },
  { code: '621320', title: 'Offices of Optometrists' },
  { code: '621330', title: 'Offices of Mental Health Practitioners' },
  { code: '621340', title: 'Offices of Physical, Occupational and Speech Therapists' },
  { code: '621391', title: 'Offices of Podiatrists' },
  { code: '621399', title: 'Offices of All Other Miscellaneous Health Practitioners' },
  { code: '621410', title: 'Family Planning Centers' },
  { code: '621420', title: 'Outpatient Mental Health and Substance Abuse Centers' },
  { code: '621491', title: 'HMO Medical Centers' },
  { code: '621492', title: 'Kidney Dialysis Centers' },
  { code: '621493', title: 'Freestanding Ambulatory Surgical and Emergency Centers' },
  { code: '621498', title: 'All Other Outpatient Care Centers' },
  { code: '621511', title: 'Medical Laboratories' },
  { code: '621512', title: 'Diagnostic Imaging Centers' },
  { code: '621610', title: 'Home Health Care Services' },
  { code: '621910', title: 'Ambulance Services' },
  { code: '621991', title: 'Blood and Organ Banks' },
  { code: '621999', title: 'All Other Miscellaneous Ambulatory Health Care Services' },
  { code: '622110', title: 'General Medical and Surgical Hospitals' },
  { code: '622210', title: 'Psychiatric and Substance Abuse Hospitals' },
  { code: '622310', title: 'Specialty (except Psychiatric and Substance Abuse) Hospitals' },
  { code: '623110', title: 'Nursing Care Facilities (Skilled Nursing Facilities)' },
  { code: '623210', title: 'Residential Intellectual and Developmental Disability Facilities' },
  { code: '623220', title: 'Residential Mental Health and Substance Abuse Facilities' },
  { code: '623311', title: 'Continuing Care Retirement Communities' },
  { code: '623312', title: 'Assisted Living Facilities for the Elderly' },
  { code: '623990', title: 'Other Residential Care Facilities' },
  { code: '624110', title: 'Child and Youth Services' },
  { code: '624120', title: 'Services for the Elderly and Persons with Disabilities' },
  { code: '624190', title: 'Other Individual and Family Services' },
  { code: '624210', title: 'Community Food Services' },
  { code: '624221', title: 'Temporary Shelters' },
  { code: '624229', title: 'Other Community Housing Services' },
  { code: '624230', title: 'Emergency and Other Relief Services' },
  { code: '624310', title: 'Vocational Rehabilitation Services' },
  { code: '624410', title: 'Child Day Care Services' },

  // 71 – Arts, Entertainment, and Recreation
  { code: '711110', title: 'Theater Companies and Dinner Theaters' },
  { code: '711120', title: 'Dance Companies' },
  { code: '711130', title: 'Musical Groups and Artists' },
  { code: '711190', title: 'Other Performing Arts Companies' },
  { code: '711211', title: 'Sports Teams and Clubs' },
  { code: '711212', title: 'Racetracks' },
  { code: '711219', title: 'Other Spectator Sports' },
  { code: '711310', title: 'Promoters of Performing Arts, Sports, and Similar Events with Facilities' },
  { code: '711320', title: 'Promoters of Performing Arts, Sports, and Similar Events without Facilities' },
  { code: '711410', title: 'Agents and Managers for Artists, Athletes, Entertainers' },
  { code: '711510', title: 'Independent Artists, Writers, and Performers' },
  { code: '712110', title: 'Museums' },
  { code: '712120', title: 'Historical Sites' },
  { code: '712130', title: 'Zoos and Botanical Gardens' },
  { code: '712190', title: 'Nature Parks and Other Similar Institutions' },
  { code: '713110', title: 'Amusement and Theme Parks' },
  { code: '713120', title: 'Amusement Arcades' },
  { code: '713210', title: 'Casinos (except Casino Hotels)' },
  { code: '713290', title: 'Other Gambling Industries' },
  { code: '713910', title: 'Golf Courses and Country Clubs' },
  { code: '713920', title: 'Skiing Facilities' },
  { code: '713930', title: 'Marinas' },
  { code: '713940', title: 'Fitness and Recreational Sports Centers' },
  { code: '713950', title: 'Bowling Centers' },
  { code: '713990', title: 'All Other Amusement and Recreation Industries' },

  // 72 – Accommodation and Food Services
  { code: '721110', title: 'Hotels (except Casino Hotels) and Motels' },
  { code: '721120', title: 'Casino Hotels' },
  { code: '721191', title: 'Bed-and-Breakfast Inns' },
  { code: '721199', title: 'All Other Traveler Accommodation' },
  { code: '721211', title: 'RV (Recreational Vehicle) Parks and Campgrounds' },
  { code: '721310', title: 'Rooming and Boarding Houses, Dormitories, and Workers Camps' },
  { code: '722310', title: 'Food Service Contractors' },
  { code: '722320', title: 'Caterers' },
  { code: '722330', title: 'Mobile Food Services' },
  { code: '722410', title: 'Drinking Places (Alcoholic Beverages)' },
  { code: '722511', title: 'Full-Service Restaurants' },
  { code: '722513', title: 'Limited-Service Restaurants' },
  { code: '722514', title: 'Cafeterias, Grill Buffets, and Buffets' },
  { code: '722515', title: 'Snack and Nonalcoholic Beverage Bars' },

  // 81 – Other Services
  { code: '811111', title: 'General Automotive Repair' },
  { code: '811112', title: 'Automotive Exhaust System Repair' },
  { code: '811113', title: 'Automotive Transmission Repair' },
  { code: '811118', title: 'Other Automotive Mechanical and Electrical Repair' },
  { code: '811121', title: 'Automotive Body, Paint, and Interior Repair and Maintenance' },
  { code: '811191', title: 'Automotive Oil Change and Lubrication Shops' },
  { code: '811192', title: 'Car Washes' },
  { code: '811198', title: 'All Other Automotive Repair and Maintenance' },
  { code: '811211', title: 'Consumer Electronics Repair and Maintenance' },
  { code: '811212', title: 'Computer and Office Machine Repair and Maintenance' },
  { code: '811213', title: 'Communication Equipment Repair and Maintenance' },
  { code: '811219', title: 'Other Electronic and Precision Equipment Repair and Maintenance' },
  { code: '811310', title: 'Commercial and Industrial Machinery and Equipment Repair and Maintenance' },
  { code: '811411', title: 'Home and Garden Equipment Repair and Maintenance' },
  { code: '811412', title: 'Appliance Repair and Maintenance' },
  { code: '811430', title: 'Footwear and Leather Goods Repair' },
  { code: '811490', title: 'Other Personal and Household Goods Repair and Maintenance' },
  { code: '812111', title: 'Barber Shops' },
  { code: '812112', title: 'Beauty Salons' },
  { code: '812113', title: 'Nail Salons' },
  { code: '812190', title: 'Other Personal Care Services' },
  { code: '812210', title: 'Funeral Homes and Funeral Services' },
  { code: '812220', title: 'Cemeteries and Crematories' },
  { code: '812310', title: 'Coin-Operated Laundries and Drycleaners' },
  { code: '812320', title: 'Drycleaning and Laundry Services (except Coin-Operated)' },
  { code: '812331', title: 'Linen Supply' },
  { code: '812332', title: 'Industrial Launderers' },
  { code: '812910', title: 'Pet Care (except Veterinary) Services' },
  { code: '812921', title: 'Photofinishing Laboratories (except One-Hour)' },
  { code: '812922', title: 'One-Hour Photofinishing' },
  { code: '812930', title: 'Parking Lots and Garages' },
  { code: '812990', title: 'All Other Personal Services' },
  { code: '813110', title: 'Religious Organizations' },
  { code: '813211', title: 'Grantmaking Foundations' },
  { code: '813212', title: 'Voluntary Health Organizations' },
  { code: '813219', title: 'Other Grantmaking and Giving Services' },
  { code: '813311', title: 'Human Rights Organizations' },
  { code: '813312', title: 'Environment, Conservation and Wildlife Organizations' },
  { code: '813319', title: 'Other Social Advocacy Organizations' },
  { code: '813410', title: 'Civic and Social Organizations' },
  { code: '813910', title: 'Business Associations' },
  { code: '813920', title: 'Professional Organizations' },
  { code: '813930', title: 'Labor Unions and Similar Labor Organizations' },
  { code: '813940', title: 'Political Organizations' },
  { code: '813990', title: 'Other Similar Organizations (except Business, Professional, Labor, and Political)' },

  // 92 – Public Administration
  { code: '921110', title: 'Executive Offices' },
  { code: '921120', title: 'Legislative Bodies' },
  { code: '921130', title: 'Public Finance Activities' },
  { code: '921140', title: 'Executive and Legislative Offices, Combined' },
  { code: '921150', title: 'American Indian and Alaska Native Tribal Governments' },
  { code: '921190', title: 'Other General Government Support' },
  { code: '922110', title: 'Courts' },
  { code: '922120', title: 'Police Protection' },
  { code: '922130', title: 'Legal Counsel and Prosecution' },
  { code: '922140', title: 'Correctional Institutions' },
  { code: '922150', title: 'Parole Offices and Probation Offices' },
  { code: '922160', title: 'Fire Protection' },
  { code: '922190', title: 'Other Justice, Public Order, and Safety Activities' },
  { code: '923110', title: 'Administration of Education Programs' },
  { code: '923120', title: 'Administration of Public Health Programs' },
  { code: '923130', title: 'Administration of Human Resource Programs' },
  { code: '923140', title: 'Administration of Veteran Affairs' },
  { code: '924110', title: 'Administration of Air and Water Resource and Solid Waste Management Programs' },
  { code: '924120', title: 'Administration of Conservation Programs' },
  { code: '925110', title: 'Administration of Housing Programs' },
  { code: '925120', title: 'Administration of Urban Planning and Community and Rural Development' },
  { code: '926110', title: 'Administration of General Economic Programs' },
  { code: '926120', title: 'Regulation and Administration of Transportation Programs' },
  { code: '926130', title: 'Regulation and Administration of Communications, Electric, Gas, and Other Utilities' },
  { code: '926140', title: 'Regulation of Agricultural Marketing and Commodities' },
  { code: '926150', title: 'Regulation, Licensing, and Inspection of Miscellaneous Commercial Sectors' },
  { code: '927110', title: 'Space Research and Technology' },
  { code: '928110', title: 'National Security' },
  { code: '928120', title: 'International Affairs' },
]

export function searchNAICS(query: string): NAICSCode[] {
  if (!query.trim()) return NAICS_CODES.slice(0, 50)
  const q = query.toLowerCase()
  return NAICS_CODES.filter(
    n =>
      n.code.includes(q) ||
      n.title.toLowerCase().includes(q) ||
      (n.description && n.description.toLowerCase().includes(q))
  ).slice(0, 100)
}

export function getNAICSByCode(code: string): NAICSCode | undefined {
  return NAICS_CODES.find(n => n.code === code)
}
